apiVersion: v1
kind: Secret
metadata:
  name: annengine-google-cloud-key
type: Opaque
data:
  {{- $files := .Files }}
  {{- range .Values.annotation.secretFiles }}
    {{ .name  }}: {{ .value }}
  {{- end }}
