apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: annotationengine-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: annotationengine
  minReplicas: {{ .Values.annotation.minReplicas | default 1 }}
  maxReplicas: {{ .Values.annotation.maxReplicas | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75