kind: Service
apiVersion: v1
metadata:
  name: annotation-service
  labels:
    tier: dynamicmicroservice
spec:
  type: NodePort
  selector:
    app: annotationengine
  ports:
    - port: 80
      targetPort: 80