
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: meshing-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meshing
  minReplicas: {{ .Values.pychunkedgraph.meshingMinReplicas | default 1}}
  maxReplicas: {{ .Values.pychunkedgraph.meshingMaxReplicas | default 10}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100