
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: $LETSENCRYPT_ISSUER_NAME
spec:
  acme:
    # The ACME server URL
    server: $LETSENCRYPT_SERVER
    # Email address used for ACME registration
    email: $LETSENCRYPT_EMAIL
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: $LETSENCRYPT_ISSUER_NAME
    solvers:
    - dns01:
        cloudDNS:
          project: $PROJECT_NAME
          serviceAccountSecretRef:
            name: $CLOUD_DNS_SERVICE_ACCOUNT_SECRET
            key: $GOOGLE_SECRET_FILENAME


