apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: $ENVIRONMENT-cert
spec:
  secretName: $ENVIRONMENT-cert
  renewBefore: 720h
  dnsNames: ${DNS_HOSTNAMES_DASHED}
  issuerRef:
    name: $LETSENCRYPT_ISSUER_NAME
