apiVersion: v1
kind: ConfigMap
metadata:
  name: dash-config-v${DASH_CONFIG_VERSION}
  namespace: default
data:
  config.py: |
${DASH_CONFIG}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dash-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dash
  minReplicas: ${DASH_MIN_REPLICAS}
  maxReplicas: ${DASH_MAX_REPLICAS}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Pods
      pods:
        metric:
          name: custom.googleapis.com|http|uwsgi_perc_busy_workers
        target:
          type: AverageValue
          averageValue: 75
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: 75
---
kind: Service
apiVersion: v1
metadata:
  name: dash-service
spec:
  type: NodePort
  selector:
    app: dash
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash
spec:
  selector:
    matchLabels:
      app: dash
  template:
    metadata:
      labels:
        app: dash
    spec:
      tolerations:
      - key: "pool"
        operator: "Equal"
        value: "${LIGHTWEIGHT_POOL}"
        effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${LIGHTWEIGHT_POOL}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: dash-config-volume
        configMap:
          name: dash-config-v${DASH_CONFIG_VERSION}
      containers:
      - name: dash
        image: ${DOCKER_REPOSITORY}/dashonflask:v${DASH_VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 9192
        volumeMounts:
        - name: dash-config-volume
          mountPath: /app/app/instance/
        env:
        - name: AUTH_URI
          value: ${AUTH_URI}
        - name: STICKY_AUTH_URL
          value: ${STICKY_AUTH_URL}
        - name: AUTH_URL
          value: ${AUTH_URL}
        - name: INFO_URL
          value: ${INFO_URL}
        - name: PROJECT_ID
          value: ${DATA_PROJECT_NAME}
        - name: AUTH_USE_REDIS
          value: "false"
        - name: SECRET_KEY
          value: ${DASH_SECRET_KEY}
        - name: DASH_SETTINGS
          value: /app/app/instance/config.py
        resources:
          requests:
            memory: 450Mi
            cpu: 100m
        readinessProbe:
          httpGet:
            path: /dash/
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /dash/
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 60
      - name: uwsgi-exporter
        image: caveconnectome/uwsgi-export-workers:v14
        # Exposes the metrics endpoint on 0.0.0.0:9101
        ports:
            - containerPort: 9101
        env:
        # This tells the exporter where to find the uWSGI stats server
        - name: UWSGI_STATS_URL
          value: "http://localhost:9192"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.8.0
        command: ["/monitor"]
        args:
          - --source=http://localhost:9101/metrics
          - --stackdriver-prefix=custom.googleapis.com
          - --pod-id=$(POD_ID)
          - --namespace-id=$(POD_NAMESPACE)
        env:
          # save Kubernetes metadata as environment variables for use in metrics
          - name: POD_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      - name: sysctl-buddy
        image: alpine:3.4
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            sysctl -w net.core.somaxconn=32768
            sysctl -w net.ipv4.ip_local_port_range='1024 65535'
            sleep 100
          done
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 10Mi
            cpu: 5m
