apiVersion: v1
kind: Service
metadata:
  name: ${NGINX_INGRESS_SERVICE_NAME}
  namespace: kube-system
  labels:
    app: nginx-ingress
    component: controller
    release: ${NGINX_INGRESS_CONTROLLER_NAME}
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: ${EXTERNAL_IP_ADDRESS}
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  selector:
    # Selects nginx-ingress-controller pods
    app: nginx-ingress
    component: controller
    release: ${NGINX_INGRESS_CONTROLLER_NAME}