apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pprogress-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pprogress
  minReplicas: ${PPROGRESS_MIN_REPLICAS}
  maxReplicas: ${PPROGRESS_MAX_REPLICAS}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
---
kind: Service
apiVersion: v1
metadata:
  name: pprogress-service
spec:
  type: NodePort
  selector:
    app: pprogress
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pprogress
spec:
  selector:
    matchLabels:
      app: pprogress
  template:
    metadata:
      labels:
        app: pprogress
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${LIGHTWEIGHT_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${LIGHTWEIGHT_POOL}
      # volumes:
      #   - name: google-cloud-key
      #     secret:
      #       secretName: ${PYCG_SERVICE_ACCOUNT_SECRET}
      terminationGracePeriodSeconds: 10
      containers:
        - name: pprogress
          image: ${DOCKER_REPOSITORY}/proofreadingprogress:v${PPROGRESS_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # volumeMounts:
          #   - name: google-cloud-key
          #     mountPath: /home/nginx/.cloudvolume/secrets
          # - name: pcg-config-volume
          #   mountPath: /app/pprogress/app/instance/
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}
            - name: AUTH_URI
              value: ${AUTH_URI}
            - name: STICKY_AUTH_URL
              value: ${STICKY_AUTH_URL}
            # - name: BIGTABLE_PROJECT
            #   value: ${DATA_PROJECT_NAME}
            # - name: BIGTABLE_INSTANCE
            #   value: ${BIGTABLE_INSTANCE_NAME}
            - name: AUTH_URL
              value: ${AUTH_URL}
            - name: INFO_URL
              value: ${INFO_URL}
            # - name: APP_SETTINGS
            #   value: "proofreadingprogress.app.config.BaseConfig"
            - name: PROJECT_ID
              value: ${DATA_PROJECT_NAME}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            # - name: L2CACHE_UPDATE_QUEUE
            #   value: ${L2CACHE_UPDATE_QUEUE}
            # - name: L2CACHE_EXCHANGE
            #   value: ${L2CACHE_EXCHANGE}
            - name: PPROGRESS_URL_PREFIX
              value: progress
            - name: AUTH_USE_REDIS
              value: "false"
            - name: DAF_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${CAVE_SECRET_FILENAME}
          resources:
            requests:
              memory: 300Mi
              cpu: 200m
          readinessProbe:
            httpGet:
              path: /progress/api/v1
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /progress/api/v1
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 60
        - name: sysctl-buddy
          image: alpine:3.4
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                sysctl -w net.core.somaxconn=32768
                sysctl -w net.ipv4.ip_local_port_range='1024 65535'
                sleep 100
              done
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 10Mi
              cpu: 5m
