apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config-v${PROXY_CONFIG_VERSION}
data:
  config.cfg: |
    PROXY_MAP = $PROXY_MAP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: proxy-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proxy
  minReplicas: ${PROXY_MIN_REPLICAS}
  maxReplicas: ${PROXY_MAX_REPLICAS}
  targetCPUUtilizationPercentage: 50
---
kind: Service
apiVersion: v1
metadata:
  name: proxy-service
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: proxy
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${LIGHTWEIGHT_POOL}"
          effect: "NoSchedule"
      volumes:
        - name: proxyservice-config-volume
          configMap:
            name: proxy-config-v${PROXY_CONFIG_VERSION}
      containers:
        - name: proxy
          image: gcr.io/${DATA_PROJECT_NAME}/middle_auth_proxy:v${PROXY_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: proxyservice-config-volume
              mountPath: /app/config/
          env:
            - name: AUTH_URI
              value: ${AUTH_URI}
            - name: STICKY_AUTH_URL
              value: ${STICKY_AUTH_URL}
            - name: AUTH_URL
              value: ${AUTH_URL}
            - name: URL_PREFIX
              value: proxy
            - name: PROXY_CONFIG_SETTINGS
              value: /app/config/config.cfg
          resources:
            requests:
              memory: 300Mi
              cpu: 100m
          readinessProbe:
            httpGet:
              path: /proxy
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /proxy
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 60
        - name: sysctl-buddy
          image: alpine:3.4
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                sysctl -w net.core.somaxconn=32768
                sysctl -w net.ipv4.ip_local_port_range='1024 65535'
                sleep 10
              done
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 10Mi
              cpu: 5m
