apiVersion: v1
kind: ConfigMap
metadata:
  name: pychunkedgraph-config-v${PCG_CONFIG_VERSION}
  namespace: default
data:
  config.cfg: |
${PCG_CONFIG}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pychunkedgraph-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pychunkedgraph
  minReplicas: ${PYCG_MIN_REPLICAS}
  maxReplicas: ${PYCG_MAX_REPLICAS}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 110
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pychunkedgraph-read-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pychunkedgraph-read
  minReplicas: ${PYCG_READ_MIN_REPLICAS}
  maxReplicas: ${PYCG_READ_MAX_REPLICAS}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 110
---
kind: Service
apiVersion: v1
metadata:
  name: pychunkedgraph-service
spec:
  type: NodePort
  selector:
    app: pychunkedgraph
  ports:
    - port: 80
      targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: pychunkedgraph-read-service
spec:
  type: NodePort
  selector:
    app: pychunkedgraph-read
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pychunkedgraph
spec:
  selector:
    matchLabels:
      app: pychunkedgraph
  template:
    metadata:
      labels:
        app: pychunkedgraph
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${STANDARD_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${STANDARD_POOL}
      volumes:
        - name: google-cloud-key
          secret:
            secretName: ${PYCG_SERVICE_ACCOUNT_SECRET}
        - name: pcg-config-volume
          configMap:
            name: pychunkedgraph-config-v${PCG_CONFIG_VERSION}
      terminationGracePeriodSeconds: 605
      containers:
        - name: pychunkedgraph
          image: ${DOCKER_REPOSITORY}/pychunkedgraph:v${PYCG_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: google-cloud-key
              mountPath: /home/nginx/.cloudvolume/secrets
            - name: pcg-config-volume
              mountPath: /app/pychunkedgraph/app/instance/
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}
            - name: MANIFEST_CACHE_REDIS_HOST
              value: "${PCG_REDIS_IP}"
            - name: REDISHOST
              value: ${REDIS_HOST}
            - name: AUTH_URI
              value: ${AUTH_URI}
            - name: STICKY_AUTH_URL
              value: ${STICKY_AUTH_URL}
            - name: BIGTABLE_PROJECT
              value: ${DATA_PROJECT_NAME}
            - name: BIGTABLE_INSTANCE
              value: ${BIGTABLE_INSTANCE_NAME}
            - name: AUTH_URL
              value: ${AUTH_URL}
            - name: INFO_URL
              value: ${INFO_URL}
            - name: REDIS_SERVICE_HOST
              value: ${REDIS_HOST}
            - name: REDIS_SERVICE_PORT
              value: "6379"
            - name: APP_SETTINGS
              value: "pychunkedgraph.app.config.DevelopmentConfig"
            - name: PROJECT_ID
              value: ${DATA_PROJECT_NAME}
            - name: SEGMENTATION_URL_PREFIX
              value: segmentation
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: PYCHUNKEDGRAPH_REMESH_QUEUE
              value: ${PYCHUNKEDGRAPH_REMESH_QUEUE}
            - name: PYCHUNKEDGRAPH_EDITS_EXCHANGE
              value: ${PYCHUNKEDGRAPH_EDITS_EXCHANGE}
            - name: PYCHUNKEDGRAPH_EDITS_LOW_PRIORITY_EXCHANGE
              value: ${PYCHUNKEDGRAPH_LOW_PRIORITY_EXCHANGE}
            - name: PCG_SERVER_LOGS_PROJECT
              value: ${PROJECT_NAME}
            - name: PCG_SERVER_LOGS_NS
              value: pcg_server_logs_${ENVIRONMENT}
            - name: PCG_SERVER_ENABLE_LOGS
              value: ${PCG_SERVER_ENABLE_LOGS}
            - name: PCG_SERVER_LOGS_LEAVES_MANY
              value: ${PCG_SERVER_LOGS_LEAVES_MANY}
            - name: PCG_GRAPH_IDS
              value: ${PCG_GRAPH_IDS}
            - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
              value: ${PCG_EDIT_PROTO_BACKEND}
            - name: ZSTD_THREADS
              value: "4"
            - name: MESHING_URL_PREFIX
              value: meshing
            - name: AUTH_USE_REDIS
              value: "false"
            - name: DAF_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${CAVE_SECRET_FILENAME}
          resources:
            requests:
              memory: ${PYCG_MEM_GIB}Gi
              cpu: ${PYCG_MILLI_CPU}m
          readinessProbe:
            httpGet:
              path: /segmentation
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /segmentation
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 60
        - name: sysctl-buddy
          image: alpine:3.4
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                sysctl -w net.core.somaxconn=32768
                sysctl -w net.ipv4.ip_local_port_range='1024 65535'
                sleep 100
              done
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 10Mi
              cpu: 5m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pychunkedgraph-read
spec:
  selector:
    matchLabels:
      app: pychunkedgraph-read
  template:
    metadata:
      labels:
        app: pychunkedgraph-read
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${STANDARD_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${STANDARD_POOL}
      volumes:
        - name: google-cloud-key
          secret:
            secretName: ${PYCG_SERVICE_ACCOUNT_SECRET}
        - name: pcg-config-volume
          configMap:
            name: pychunkedgraph-config-v${PCG_CONFIG_VERSION}
      terminationGracePeriodSeconds: 15
      containers:
        - name: pychunkedgraph
          image: ${DOCKER_REPOSITORY}/pychunkedgraph:v${PYCG_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: google-cloud-key
              mountPath: /home/nginx/.cloudvolume/secrets
            - name: pcg-config-volume
              mountPath: /app/pychunkedgraph/app/instance/
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}
            - name: MANIFEST_CACHE_REDIS_HOST
              value: "${PCG_REDIS_IP}"
            - name: REDISHOST
              value: ${REDIS_HOST}
            - name: AUTH_URI
              value: ${AUTH_URI}
            - name: STICKY_AUTH_URL
              value: ${STICKY_AUTH_URL}
            - name: BIGTABLE_PROJECT
              value: ${DATA_PROJECT_NAME}
            - name: BIGTABLE_INSTANCE
              value: ${BIGTABLE_INSTANCE_NAME}
            - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
              value: "upb"
            - name: ZSTD_THREADS
              value: "2"
            - name: AUTH_URL
              value: ${AUTH_URL}
            - name: INFO_URL
              value: ${INFO_URL}
            - name: REDIS_SERVICE_HOST
              value: ${REDIS_HOST}
            - name: REDIS_SERVICE_PORT
              value: "6379"
            - name: APP_SETTINGS
              value: "pychunkedgraph.app.config.DevelopmentConfig"
            - name: PROJECT_ID
              value: ${DATA_PROJECT_NAME}
            - name: SEGMENTATION_URL_PREFIX
              value: segmentation
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: PYCHUNKEDGRAPH_REMESH_QUEUE
              value: ${PYCHUNKEDGRAPH_REMESH_QUEUE}
            - name: PYCHUNKEDGRAPH_EDITS_EXCHANGE
              value: ${PYCHUNKEDGRAPH_EDITS_EXCHANGE}
            - name: PYCHUNKEDGRAPH_EDITS_LOW_PRIORITY_EXCHANGE
              value: ${PYCHUNKEDGRAPH_LOW_PRIORITY_EXCHANGE}
            - name: PCG_SERVER_LOGS_PROJECT
              value: ${PROJECT_NAME}
            - name: PCG_SERVER_LOGS_NS
              value: pcg_server_logs_${ENVIRONMENT}
            - name: PCG_SERVER_ENABLE_LOGS
              value: ${PCG_SERVER_ENABLE_LOGS}
            - name: PCG_SERVER_LOGS_LEAVES_MANY
              value: ${PCG_SERVER_LOGS_LEAVES_MANY}
            - name: PCG_GRAPH_IDS
              value: ${PCG_GRAPH_IDS}
            - name: MESHING_URL_PREFIX
              value: meshing
            - name: AUTH_USE_REDIS
              value: "false"
            - name: DAF_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${CAVE_SECRET_FILENAME}
          resources:
            requests:
              memory: ${PYCG_READ_MEM_GIB}Gi
              cpu: ${PYCG_READ_MILLI_CPU}m
          readinessProbe:
            httpGet:
              path: /segmentation
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /segmentation
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 60
        - name: sysctl-buddy
          image: alpine:3.4
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                sysctl -w net.core.somaxconn=32768
                sysctl -w net.ipv4.ip_local_port_range='1024 65535'
                sleep 100
              done
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 10Mi
              cpu: 5m
