# env configmaps from values
apiVersion: v1
kind: ConfigMap
metadata:
  name: cg-jobs-common
data:
  SHELL: "/bin/bash"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: repair-edit-operations-repair-info
data:
  DATASTORE_NS: "pcg_operation_log"
  GRAPH_IDS: "${PCG_GRAPH_IDS}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: repair-edit-operations-pychunkedgraph
data:
  BIGTABLE_INSTANCE: "${BIGTABLE_INSTANCE_NAME}"
  BIGTABLE_PROJECT: "${DATA_PROJECT_NAME}"
  GOOGLE_APPLICATION_CREDENTIALS: "/root/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}"
  OPERATION_LOGS_DATASTORE_CREDENTIALS: "/root/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: export-operation-logs-export-info
data:
  DATASTORE_NS: "pcg_operation_log"
  EMAIL_LIST_FAILED_WRITES: "${PCG_OPERATION_EMAIL_LIST}"
  GRAPH_IDS: "${PCG_GRAPH_IDS}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: export-operation-logs-pychunkedgraph
data:
  ALERT_BOT_EMAIL_ID: "${PCG_EMAIL_ACCOUNT}"
  ALERT_BOT_EMAIL_PASSWORD: "${PCG_EMAIL_PASSWORD}"
  BIGTABLE_INSTANCE: "${BIGTABLE_INSTANCE_NAME}"
  BIGTABLE_PROJECT: "${DATA_PROJECT_NAME}"
  GOOGLE_APPLICATION_CREDENTIALS: "/root/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}"
  OPERATION_LOGS_DATASTORE_CREDENTIALS: "/root/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "export-operation-logs"
spec:
  schedule: "@hourly"
  startingDeadlineSeconds: 150
  suspend: ${PCG_CRONJOB_SUSPENDED}
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: ${STANDARD_POOL}
          volumes:
            - name: "google-secret"
              secret:
                secretName: ${PYCG_SERVICE_ACCOUNT_SECRET}
          containers:
            - name: "export-operation-logs"
              image: ${DOCKER_REPOSITORY}/pychunkedgraph:v${PYCG_VERSION}
              imagePullPolicy: "Always"
              resources:
                requests:
                  memory: 12G
              envFrom:
                - configMapRef:
                    name: cg-jobs-common
                - configMapRef:
                    name: export-operation-logs-export-info
                - configMapRef:
                    name: export-operation-logs-pychunkedgraph
              volumeMounts:
                - name: "google-secret"
                  mountPath: /root/.cloudvolume/secrets
                  readOnly: true
              command:
                - bash
                - -c
                - python -m pychunkedgraph.jobs.export.datastore.operation_logs
          restartPolicy: OnFailure
          # nodeSelector:
          #   cloud.google.com/gke-nodepool: master
