apiVersion: v1
kind: ConfigMap
metadata:
  name: skeletoncache-config-v${SKELETONCACHE_CONFIG_VERSION}
  namespace: default
data:
  config.cfg: |
    SKELETON_CACHE_BUCKET = "gs://${SKELETON_CACHE_BUCKET}"
    SKELETONCACHE_MAX_REPLICAS = ${SKELETONCACHE_MAX_REPLICAS}
---
apiVersion: v1
kind: Service
metadata:
  name: skeletoncache-service
spec:
  type: NodePort
  selector:
    app: skeletoncache
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skeletoncache-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skeletoncache
  minReplicas: ${SKELETONCACHE_MIN_REPLICAS}
  maxReplicas: ${SKELETONCACHE_MAX_REPLICAS}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeletoncache
spec:
  selector:
    matchLabels:
      app: skeletoncache
  template:
    metadata:
      labels:
        app: skeletoncache
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${MESH_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${MESH_POOL}
      volumes:
        - name: google-cloud-key
          secret:
            secretName: ${SKELETON_SERVICE_ACCOUNT_SECRET}
        - name: skeleton-config-volume
          configMap:
            name: skeletoncache-config-v${SKELETONCACHE_CONFIG_VERSION}
      terminationGracePeriodSeconds: 10
      containers:
        - name: skeletoncache
          image: ${DOCKER_REPOSITORY}/skeletoncache:v${SKELETONCACHE_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: google-cloud-key
              mountPath: /home/nginx/.cloudvolume/secrets
            - name: skeleton-config-volume
              mountPath: /app/skeletoncache/app/instance/
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}
            - name: GLOBAL_SERVER_URL
              value: https://${GLOBAL_SERVER}
            - name: AUTH_URI
              value: ${AUTH_URI}
            - name: STICKY_AUTH_URL
              value: ${STICKY_AUTH_URL}
            - name: AUTH_URL
              value: ${AUTH_URL}
            - name: INFO_URL
              value: ${INFO_URL}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: SKELETONSERVICE_SETTINGS
              value: "/app/skeletoncache/app/instance/config.cfg"
            - name: APP_SETTINGS
              value: "skeletoncache.app.config.DevelopmentConfig"
            - name: DAF_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${CAVE_SECRET_FILENAME}
            - name: SKELETON_CACHE_LOW_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_LOW_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE}
          resources:
            requests:
              memory: 600Mi
              cpu: 50m
          readinessProbe:
            httpGet:
              path: /skeletoncache/health
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /skeletoncache/health
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 60
        - name: sysctl-buddy
          image: alpine:3.4
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                sysctl -w net.core.somaxconn=32768
                sysctl -w net.ipv4.ip_local_port_range='1024 65535'
                sleep 100
              done
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 10Mi
              cpu: 5m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skeletoncache-worker-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skeletoncache-worker
  minReplicas: ${SKELETONCACHE_WORKER_MIN_REPLICAS}
  maxReplicas: ${SKELETONCACHE_WORKER_MAX_REPLICAS}
  metrics:
    - external:
        metric:
          name: pubsub.googleapis.com|subscription|num_undelivered_messages
          selector:
            matchLabels:
              resource.labels.subscription_id: ${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE}
              resource.labels.subscription_id: ${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE}
        target:
          type: AverageValue
          averageValue: 1
      type: External
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeletoncache-worker
spec:
  selector:
    matchLabels:
      app: skeletoncache-worker
  template:
    metadata:
      labels:
        app: skeletoncache-worker
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${MESH_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${MESH_POOL}
      volumes:
        - name: google-cloud-key
          secret:
            secretName: ${SKELETON_SERVICE_ACCOUNT_SECRET}
        - name: sksv-config-volume
          configMap:
            name: skeletoncache-config-v${SKELETONCACHE_CONFIG_VERSION}
      terminationGracePeriodSeconds: 10
      containers:
        - name: skeletoncache-worker
          image: ${DOCKER_REPOSITORY}/skeletoncache:v${SKELETONCACHE_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: google-cloud-key
              mountPath: /root/.cloudvolume/secrets
            - name: sksv-config-volume
              mountPath: /app/skeletoncache/app/instance/
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}
            - name: GLOBAL_SERVER_URL
              value: https://${GLOBAL_SERVER}
            - name: AUTH_URI
              value: ${AUTH_URI}
            - name: STICKY_AUTH_URL
              value: ${STICKY_AUTH_URL}
            - name: BIGTABLE_PROJECT
              value: ${DATA_PROJECT_NAME}
            - name: BIGTABLE_INSTANCE
              value: ${BIGTABLE_INSTANCE_NAME}
            - name: AUTH_URL
              value: ${AUTH_URL}
            - name: INFO_URL
              value: ${INFO_URL}
            - name: APP_SETTINGS
              value: "skeletoncache.app.config.DevelopmentConfig"
            - name: SKELETON_CACHE_URL_PREFIX
              value: sksv
            - name: PROJECT_ID
              value: ${DATA_PROJECT_NAME}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: SKELETON_CACHE_LOW_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_LOW_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE}
            - name: AUTH_USE_REDIS
              value: "false"
            - name: DAF_CREDENTIALS
              value: /root/.cloudvolume/secrets/${CAVE_SECRET_FILENAME}
          resources:
            requests:
              memory: 2500Mi
              cpu: 250m
          command:
            - /bin/sh
            - -c
            - python -u -m skeletonservice.datasets.messaging
            
