apiVersion: v1
kind: ConfigMap
metadata:
  name: skeletoncache-config-v${SKELETONCACHE_CONFIG_VERSION}
  namespace: default
data:
  config.cfg: |
    SKELETON_CACHE_BUCKET = "gs://${SKELETON_CACHE_BUCKET}"
    SKELETONCACHE_MAX_REPLICAS = ${SKELETONCACHE_MAX_REPLICAS}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-read-pods-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: kubernetes-read-pods-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: skeletoncache-service
spec:
  type: NodePort
  selector:
    app: skeletoncache
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skeletoncache-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skeletoncache
  minReplicas: ${SKELETONCACHE_MIN_REPLICAS}
  maxReplicas: ${SKELETONCACHE_MAX_REPLICAS}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Pods
      pods:
        metric:
          name: custom.googleapis.com|http|uwsgi_perc_busy_workers
        target:
          type: AverageValue
          averageValue: 75
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeletoncache
spec:
  selector:
    matchLabels:
      app: skeletoncache
  template:
    metadata:
      labels:
        app: skeletoncache
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${MESH_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${MESH_POOL}
      volumes:
        - name: google-cloud-key
          secret:
            secretName: ${SKELETON_SERVICE_ACCOUNT_SECRET}
        - name: skeleton-config-volume
          configMap:
            name: skeletoncache-config-v${SKELETONCACHE_CONFIG_VERSION}
      terminationGracePeriodSeconds: 10
      containers:
        - name: skeletoncache
          image: ${DOCKER_REPOSITORY}/skeletoncache:v${SKELETONCACHE_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: google-cloud-key
              mountPath: /home/nginx/.cloudvolume/secrets
            - name: skeleton-config-volume
              mountPath: /app/skeletoncache/app/instance/
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}
            - name: GLOBAL_SERVER_URL
              value: https://${GLOBAL_SERVER}
            - name: AUTH_URI
              value: ${AUTH_URI}
            - name: STICKY_AUTH_URL
              value: ${STICKY_AUTH_URL}
            - name: AUTH_URL
              value: ${AUTH_URL}
            - name: INFO_URL
              value: ${INFO_URL}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: LIMITER_CATEGORIES
              value: "${SK_LIMITER_CATEGORIES}"
            - name: LIMITER_URI
              value: ${LIMITER_URI}
            - name: SKELETONSERVICE_SETTINGS
              value: "/app/skeletoncache/app/instance/config.cfg"
            - name: APP_SETTINGS
              value: "skeletoncache.app.config.DevelopmentConfig"
            - name: DAF_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${CAVE_SECRET_FILENAME}
            - name: CACHE_NON_H5_SKELETONS
              value: "false"
            - name: SKELETON_DATASTACK_NAME_REMAPPING
              value: ${SKELETON_DATASTACK_NAME_REMAPPING}
            - name: SKELETONCACHE_WORKER_MAX_REPLICAS
              value: "${SKELETONCACHE_WORKER_MAX_REPLICAS}"
            - name: SKELETON_CACHE_LOW_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_LOW_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE}
            - name: SKELETON_CACHE_DEAD_LETTER_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_DEAD_LETTER_RETRIEVE_QUEUE}
            - name: VERBOSE_LEVEL
              value: "0"
            - name: DEBUG_ROOT_ID
              value: "864691137021499502"
          resources:
            requests:
              memory: 600Mi
              cpu: 50m
          readinessProbe:
            httpGet:
              path: /skeletoncache/health
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /skeletoncache/health
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 60
        - name: uwsgi-exporter
          image: caveconnectome/uwsgi-export-workers:v14
          # Exposes the metrics endpoint on 0.0.0.0:9101
          ports:
             - containerPort: 9101
          env:
          # This tells the exporter where to find the uWSGI stats server
          - name: UWSGI_STATS_URL
            value: "http://localhost:1717"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: prometheus-to-sd
          image: gcr.io/google-containers/prometheus-to-sd:v0.8.0
          command: ["/monitor"]
          args:
            - --source=http://localhost:9101/metrics
            - --stackdriver-prefix=custom.googleapis.com
            - --pod-id=$(POD_ID)
            - --namespace-id=$(POD_NAMESPACE)
          env:
            # save Kubernetes metadata as environment variables for use in metrics
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        - name: sysctl-buddy
          image: alpine:3.4
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                sysctl -w net.core.somaxconn=32768
                sysctl -w net.ipv4.ip_local_port_range='1024 65535'
                sleep 100
              done
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 10Mi
              cpu: 5m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skeletoncache-worker-scaler
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skeletoncache-worker
  minReplicas: ${SKELETONCACHE_WORKER_MIN_REPLICAS}
  maxReplicas: ${SKELETONCACHE_WORKER_MAX_REPLICAS}
  metrics:
    - type: External
      external:
        metric:
          name: custom.googleapis.com|pubsub|undelivered_per_worker_${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE_SAFE_LOWER}
        target:
          type: Value
          value: "1.5" 
    - type: External
      external:
        metric:
          name: custom.googleapis.com|pubsub|undelivered_per_worker_${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE_SAFE_LOWER}
        target:
          type: Value
          value: "1.5"  
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: skeleton-worker-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skeletoncache-worker
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: 'skeletoncache-worker'
      minAllowed:
        cpu: 50m     
        memory: 200Mi 
      maxAllowed:
        cpu: 1000m        
        memory: 2Gi    
      controlledResources: ["cpu", "memory"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeletoncache-worker
spec:
  selector:
    matchLabels:
      app: skeletoncache-worker
  template:
    metadata:
      labels:
        app: skeletoncache-worker
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${MESH_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${MESH_POOL}
      volumes:
        - name: google-cloud-key
          secret:
            secretName: ${SKELETON_SERVICE_ACCOUNT_SECRET}
        - name: sksv-config-volume
          configMap:
            name: skeletoncache-config-v${SKELETONCACHE_CONFIG_VERSION}
      terminationGracePeriodSeconds: 10
      containers:
        - name: skeletoncache-worker
          image: ${DOCKER_REPOSITORY}/skeletoncache:v${SKELETONCACHE_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: google-cloud-key
              mountPath: /root/.cloudvolume/secrets
            - name: sksv-config-volume
              mountPath: /app/skeletoncache/app/instance/
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}
            - name: GLOBAL_SERVER_URL
              value: https://${GLOBAL_SERVER}
            - name: AUTH_URI
              value: ${AUTH_URI}
            - name: STICKY_AUTH_URL
              value: ${STICKY_AUTH_URL}
            - name: BIGTABLE_PROJECT
              value: ${DATA_PROJECT_NAME}
            - name: BIGTABLE_INSTANCE
              value: ${BIGTABLE_INSTANCE_NAME}
            - name: AUTH_URL
              value: ${AUTH_URL}
            - name: INFO_URL
              value: ${INFO_URL}
            - name: APP_SETTINGS
              value: "skeletoncache.app.config.DevelopmentConfig"
            - name: SKELETON_CACHE_URL_PREFIX
              value: sksv
            - name: PROJECT_ID
              value: ${DATA_PROJECT_NAME}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: CACHE_NON_H5_SKELETONS
              value: "false"
            - name: SKELETON_DATASTACK_NAME_REMAPPING
              value: ${SKELETON_DATASTACK_NAME_REMAPPING}
            - name: SKELETONCACHE_WORKER_MAX_REPLICAS
              value: "${SKELETONCACHE_WORKER_MAX_REPLICAS}"
            - name: SKELETON_CACHE_LOW_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_LOW_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE}
            - name: SKELETON_CACHE_DEAD_LETTER_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_DEAD_LETTER_RETRIEVE_QUEUE}
            - name: VERBOSE_LEVEL
              value: "0"
            - name: DEBUG_ROOT_ID
              value: "864691135359413848"
            - name: AUTH_USE_REDIS
              value: "false"
            - name: DAF_CREDENTIALS
              value: /root/.cloudvolume/secrets/${CAVE_SECRET_FILENAME}
          resources:
            requests:
              memory: 500Mi
              cpu: 50m
          command:
            - /bin/sh
            - -c
            - python -u -m skeletonservice.datasets.messaging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeletoncache-stats-exporter
spec:
  replicas: 1  # Only need one instance
  selector:
    matchLabels:
      app: skeletoncache-stats-exporter
  template:
    metadata:
      labels:
        app: skeletoncache-stats-exporter
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${MESH_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${MESH_POOL}
      volumes:
        - name: google-cloud-key
          secret:
            secretName: ${SKELETON_SERVICE_ACCOUNT_SECRET}
      terminationGracePeriodSeconds: 10
      serviceAccountName: kubernetes-read-pods-sa
      containers:
        - name: stats-exporter
          image: ${DOCKER_REPOSITORY}/uwsgi-export-workers:vpubsub_stats14
          imagePullPolicy: Always
          volumeMounts:
            - name: google-cloud-key
              mountPath: /root/.cloudvolume/secrets
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}
            - name: GOOGLE_CLOUD_PROJECT
              value: ${PROJECT_NAME}
            - name: PUBSUB_SUBSCRIPTIONS
              value: "${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE},${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE}"
            - name: CLUSTER_NAME
              value: ${CLUSTER_NAME}
            - name: CLUSTER_LOCATION
              value: ${ZONE}
            - name: WORKER_NAMESPACE
              value: default
            - name: WORKER_LABEL_SELECTOR
              value: "app=skeletoncache-worker"
            - name: EXPORTER_POLL_INTERVAL
              value: "30"  # Poll every 30 seconds for efficiency
          command:
            - /bin/sh
            - -c
            - python -u pubsub_stats_exporter.py
          resources:
            requests:
              memory: 200Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 200m
---
apiVersion: batch/v1
kind: Job
metadata:
  name: skeletoncache-integration-tester
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: skeletoncache-integration-tester
    spec:
      restartPolicy: OnFailure
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${MESH_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${MESH_POOL}
      volumes:
        - name: google-cloud-key
          secret:
            secretName: ${SKELETON_SERVICE_ACCOUNT_SECRET}
        - name: sksv-config-volume
          configMap:
            name: skeletoncache-config-v${SKELETONCACHE_CONFIG_VERSION}
      terminationGracePeriodSeconds: 10
      containers:
        - name: skeletoncache-integration-tester
          image: ${DOCKER_REPOSITORY}/skeletoncache:v${SKELETONCACHE_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: google-cloud-key
              mountPath: /root/.cloudvolume/secrets
            - name: sksv-config-volume
              mountPath: /app/skeletoncache/app/instance/
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}
            - name: GLOBAL_SERVER_URL
              value: https://${GLOBAL_SERVER}
            - name: AUTH_URI
              value: ${AUTH_URI}
            - name: STICKY_AUTH_URL
              value: ${STICKY_AUTH_URL}
            - name: BIGTABLE_PROJECT
              value: ${DATA_PROJECT_NAME}
            - name: BIGTABLE_INSTANCE
              value: ${BIGTABLE_INSTANCE_NAME}
            - name: AUTH_URL
              value: ${AUTH_URL}
            - name: INFO_URL
              value: ${INFO_URL}
            - name: APP_SETTINGS
              value: "skeletoncache.app.config.DevelopmentConfig"
            - name: SKELETON_CACHE_URL_PREFIX
              value: sksv
            - name: PROJECT_ID
              value: ${DATA_PROJECT_NAME}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: DEV_SLACK_WEBHOOK_ID
              value: "T0CL3AB5X/B08KJ36BJAF/DfcLRvJzizvCaozpMugAnu38"  # Keith Wiley's Slack direct messages
            - name: PROD_SLACK_WEBHOOK_ID
              value: "T0CL3AB5X/B08P52E7A05/iXHgqifbk8MtpDw4adoSh5pW"  # deployment-hour-alerts channel
            - name: VERBOSE_LEVEL
              value: "1"
            - name: AUTH_USE_REDIS
              value: "false"
            - name: DAF_CREDENTIALS
              value: /root/.cloudvolume/secrets/${CAVE_SECRET_FILENAME}
          resources:
            requests:
              memory: 500Mi
              cpu: 50m
          command:
            - /bin/sh
            - -c
            # You need to verify or change the value of the -d argument each time you deploy. Options are listed in the corresponding PrinceAllenCAVE config file.
            - python -u -m tests.test_integration --kube -s ${SKELETON_INTEGRATION_TEST_SERVER} -d ${SKELETON_INTEGRATION_TEST_DATASTACK__DEFAULT} -z ${ZONE} -c ${CLUSTER_NAME} -v 2
