apiVersion: v1
kind: ConfigMap
metadata:
  name: annotationengine-config
data:
  config.cfg: |
    import os
    import json
    INFOSERVICE_ENDPOINT = "https://{{ .Values.cluster.globalServer }}/info"
    SCHEMA_SERVICE_ENDPOINT = "https://{{ .Values.cluster.globalServer }}/schema/"
    GLOBAL_SERVER_URL = "https://{{ .Values.cluster.globalServer }}"
    NEUROGLANCER_URL = "https://neuroglancer-demo.appspot.com"
    SQLALCHEMY_DATABASE_URI = "postgres://{{ .Values.cloudsql.username}}:{{ .Values.cloudsql.password}}@127.0.0.1:3306/annotation"
    TESTING = False
    LOGGING_FORMAT = '%(asctime)s - %(levelname)s - %(message)s'
    LOGGING_LOCATION = '/home/nginx/annoeng/bookshelf.log'
    if os.environ.get("DAF_CREDENTIALS", None) is not None:
        with open(os.environ.get("DAF_CREDENTIALS"), "r") as f:
            AUTH_TOKEN = json.load(f)["token"]
    AUTH_SHARED_EXCLUDED_GROUPS={{ .Values.annotation.excludedPermissionGroups | toJson }}
