{{- $password := .Values.cloudsql.googleSecret | required ".Values.cloudsql.googleSecret is required." -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: mat-cloudsql-google-cloud-key
type: Opaque
data:
  google-secret.json: {{ .Values.cloudsql.googleSecret }}
