apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-consumer-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-consumer
  minReplicas: {{ .Values.materialize.consumerMinReplicas }}
  maxReplicas: {{ .Values.materialize.consumerMaxReplicas }}
  metrics:
    - type: Pods
      pods:
        metric:
          name: custom.googleapis.com|http|celery_queue_length
        target:
          type: AverageValue
          averageValue: 2