apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pychunkedgraph-read-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pychunkedgraph-read
  minReplicas: {{ .Values.pychunkedgraph.readMinReplicas | default 1}}
  maxReplicas: {{ .Values.pychunkedgraph.readMaxReplicas | default 10}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 110