
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pychunkedgraph-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pychunkedgraph
  minReplicas: {{ .Values.pychunkedgraph.writeMinReplicas | default 1}}
  maxReplicas: {{ .Values.pychunkedgraph.writeMaxReplicas | default 10}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 110