apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${environment}-cert
spec:
  secretName: ${environment}-cert
  renewBefore: 720h
  dnsNames:
%{ for dns_name in dns_names }
  - ${dns_name}
%{ endfor }
  issuerRef:
    name: ${issuer_name}