PYCG_READ_MEM_MIB=$(echo "(${PYCG_READ_MEM_GIB} * 1024) + 0.5" | bc -l | awk '{printf("%d",$0)}')
export PYCG_READ_MEM_MIB

export SKELETON_CACHE_LOW_PRIORITY_EXCHANGE="${ENVIRONMENT}_SKELETON_CACHE_LOW_PRIORITY"
export SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE="${ENVIRONMENT}_SKELETON_CACHE_HIGH_PRIORITY"
export SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE="${ENVIRONMENT}_SKELETON_CACHE_WORKER_LOW_PRIORITY"
export SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE="${ENVIRONMENT}_SKELETON_CACHE_WORKER_HIGH_PRIORITY"