PYCG_READ_MEM_MIB=$(echo "(${PYCG_READ_MEM_GIB} * 1024) + 0.5" | bc -l | awk '{printf("%d",$0)}')
export PYCG_READ_MEM_MIB

PYCG_MEM_MIB=$(echo "(${PYCG_MEM_GIB} * 1024) + 0.5" | bc -l | awk '{printf("%d",$0)}')
export PYCG_MEM_MIB

# Generate cluster name safe for use in metric names (replace dashes with underscores)
CLUSTER_NAME_SAFE=$(echo "${CLUSTER_NAME}" | sed 's/-/_/g')
export CLUSTER_NAME_SAFE

export SKELETON_CACHE_LOW_PRIORITY_EXCHANGE="${ENVIRONMENT}_SKELETON_CACHE_LOW_PRIORITY"
export SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE="${ENVIRONMENT}_SKELETON_CACHE_HIGH_PRIORITY"
export SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE="${ENVIRONMENT}_SKELETON_CACHE_WORKER_LOW_PRIORITY"
export SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE="${ENVIRONMENT}_SKELETON_CACHE_WORKER_HIGH_PRIORITY"

# Generate safe subscription names for use in metric names (replace dashes with underscores and convert to lowercase)
SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE_SAFE=$(echo "${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE}" | sed 's/-/_/g')
export SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE_SAFE

SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE_SAFE=$(echo "${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE}" | sed 's/-/_/g')
export SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE_SAFE

SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE_SAFE_LOWER=$(echo "${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE_SAFE}" | tr '[:upper:]' '[:lower:]')
export SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE_SAFE_LOWER

SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE_SAFE_LOWER=$(echo "${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE_SAFE}" | tr '[:upper:]' '[:lower:]')
export SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE_SAFE_LOWER

# if ORCHESTRATION_QUEUE_NAME is not set, default to "orchestration"
if [ -z "${ORCHESTRATION_QUEUE_NAME}" ]; then
  export ORCHESTRATION_QUEUE_NAME="orchestration"
fi