apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dash-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dash
  minReplicas: {{ .Values.dash.minReplicas | default 1}}
  maxReplicas: {{ .Values.dash.maxReplicas | default 10}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: 75